### PR TITLE
Advise user when generator is run and capyara/webrat not available

### PR DESCRIPTION
**Pull request by qnm**
The error without either installed is the enigmatic:

```
NoMethodError:
  undefined method `has_selector?' for #<ActiveSupport::SafeBuffer:0x000000054b1090>
```

When the generator is executed, this patch will warn the user that the default spec requires capybara/webrat installed.

I'm happy to write a test for this if you can point me in the right direction!

### CODE REVIEW

**Comment by qnm** [comment]
Neither are dependencies.

See the test app here - perhaps I'm missing something.

https://github.com/qnm/test-rspec-apotomo-without-capybara

**Comment by apotonick** [comment]
Should we move that to https://github.com/apotonick/rspec-apotomo/blob/master/lib/rspec-apotomo.rb ?

**Comment by qnm** [comment]
Yeah - that makes sense.

**Comment by apotonick** [comment]
Let's move it to lib/rspec/cells.rb in the rspec-cells gem!!! Are you ready? :-)

**Comment by apotonick** [comment]
Oh, rspec-cells is not a dependency. Let's move it to rspec-apotomo.rb, then.

**Comment by qnm** [comment]
> Let's move it to rspec-apotomo.rb, then.

That's what I've done, let me know if there's any further changes!

**Pull request merged**
