### PR TITLE
Loosen rails version requirement to allow for rails 4.0

### PR DESCRIPTION
**Pull request by atambo**

### CODE REVIEW

**Comment by atambo** [comment]
@apotonick, could you merge & release a new rspec-apotomo with this change so I can continue upgrading to rails 4.0?

**Comment by andreorvalho** [comment]
Hey @atambo did you get this work?

I was trying to install this on a engine with rails 4 and I get:

```
andreorvalho$ rspec spec/widgets/calendar_widget_spec.rb -bcf n
/Users/andreorvalho/projects/white_album/frontend/spec/widgets/calendar_widget_spec.rb:5:in `block in <top (required)>': undefined method `has_widgets' for #<Class:0x007fcd7b483898> (NoMethodError)
    from /Users/andreorvalho/.rvm/gems/ruby-2.0.0-p247@white_album/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:246:in `module_eval'
    from /Users/andreorvalho/.rvm/gems/ruby-2.0.0-p247@white_album/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:246:in `subclass'
    from /Users/andreorvalho/.rvm/gems/ruby-2.0.0-p247@white_album/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:232:in `describe'
    from /Users/andreorvalho/.rvm/gems/ruby-2.0.0-p247@white_album/gems/rspec-core-2.14.7/lib/rspec/core/dsl.rb:18:in `describe'
    from /Users/andreorvalho/projects/white_album/frontend/spec/widgets/calendar_widget_spec.rb:3:in `<top (required)>'
    from /Users/andreorvalho/.rvm/gems/ruby-2.0.0-p247@white_album/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:241:in `load'
    from /Users/andreorvalho/.rvm/gems/ruby-2.0.0-p247@white_album/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:241:in `block in load'
    from /Users/andreorvalho/.rvm/gems/ruby-2.0.0-p247@white_album/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:232:in `load_dependency'
    from /Users/andreorvalho/.rvm/gems/ruby-2.0.0-p247@white_album/gems/activesupport-4.1.0.rc1/lib/active_support/dependencies.rb:241:in `load'
    from /Users/andreorvalho/.rvm/gems/ruby-2.0.0-p247@white_album/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `block in load_spec_files'
    from /Users/andreorvalho/.rvm/gems/ruby-2.0.0-p247@white_album/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `each'
    from /Users/andreorvalho/.rvm/gems/ruby-2.0.0-p247@white_album/gems/rspec-core-2.14.7/lib/rspec/core/configuration.rb:896:in `load_spec_files'
    from /Users/andreorvalho/.rvm/gems/ruby-2.0.0-p247@white_album/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:22:in `run'
    from /Users/andreorvalho/.rvm/gems/ruby-2.0.0-p247@white_album/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:80:in `run'
    from /Users/andreorvalho/.rvm/gems/ruby-2.0.0-p247@white_album/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:17:in `block in autorun'
    from /Users/andreorvalho/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Users/andreorvalho/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'
```

and my code was:

``` ruby
require 'spec_helper'

describe CalendarWidget do

  has_widgets do |root|
    root << widget(:calendar)
  end

  it "renders the widget" do
    res = render_widget(:calendar)
  end
end
```

Is that something I am doing wrong? or is there still no support for rails 4?

**Comment by apotonick** [comment]
Can you try without an engine just to verify that the engine is the problem?

**Comment by andreorvalho** [comment]
@apotonick I am sorry I never answered. This was actually me forgetting to include apotomo on the engine file. thanks for the help

**Pull request merged**
